// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5XYmfVTP7WY8Z494FCG_VUwC9yH3X7kg',
    appId: '1:796187957007:web:c805fe9c5bfa170714907a',
    messagingSenderId: '796187957007',
    projectId: 'flutter-full-news-8a140',
    authDomain: 'flutter-full-news-8a140.firebaseapp.com',
    storageBucket: 'flutter-full-news-8a140.appspot.com',
    measurementId: 'G-VK3H481XPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZpubzUX4tKozBnzTijzBvQiWqIYaCcDs',
    appId: '1:796187957007:android:99c9318ea8ddd59114907a',
    messagingSenderId: '796187957007',
    projectId: 'flutter-full-news-8a140',
    storageBucket: 'flutter-full-news-8a140.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIwOBMdRBOYgv14Bz8KDX3d2R6D7QocVg',
    appId: '1:796187957007:ios:98930fe6a24accf514907a',
    messagingSenderId: '796187957007',
    projectId: 'flutter-full-news-8a140',
    storageBucket: 'flutter-full-news-8a140.appspot.com',
    iosClientId: '796187957007-00vgvpso4s2tv8s7ksqtb5hggng3mfr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseFullNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIwOBMdRBOYgv14Bz8KDX3d2R6D7QocVg',
    appId: '1:796187957007:ios:570cf41f4ac71e5a14907a',
    messagingSenderId: '796187957007',
    projectId: 'flutter-full-news-8a140',
    storageBucket: 'flutter-full-news-8a140.appspot.com',
    iosClientId: '796187957007-ebhp5gs168h2tejo56jrkh7ahee4h323.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseFullNewsApp.RunnerTests',
  );
}
